export {default as CopyRight} from './copyright'
export {default as Nav} from './nav'
export {default as H2} from './h2'
export {default as H3} from './h3'
export {default as Img} from './img'
export {default as Ptag} from './ptag'
export {default as Div} from './div'
